/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CreateJournalRouteImport } from './routes/create-journal'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutJournalIdUpdatesRouteImport } from './routes/_layout.$journalId.updates'
import { Route as LayoutJournalIdTasksRouteImport } from './routes/_layout.$journalId.tasks'
import { Route as LayoutJournalIdNotesRouteImport } from './routes/_layout.$journalId.notes'
import { Route as LayoutJournalIdBookmarkedRouteImport } from './routes/_layout.$journalId.bookmarked'
import { Route as LayoutJournalIdTagsTagIdRouteImport } from './routes/_layout.$journalId.tags.$tagId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateJournalRoute = CreateJournalRouteImport.update({
  id: '/create-journal',
  path: '/create-journal',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutJournalIdUpdatesRoute = LayoutJournalIdUpdatesRouteImport.update({
  id: '/$journalId/updates',
  path: '/$journalId/updates',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutJournalIdTasksRoute = LayoutJournalIdTasksRouteImport.update({
  id: '/$journalId/tasks',
  path: '/$journalId/tasks',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutJournalIdNotesRoute = LayoutJournalIdNotesRouteImport.update({
  id: '/$journalId/notes',
  path: '/$journalId/notes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutJournalIdBookmarkedRoute =
  LayoutJournalIdBookmarkedRouteImport.update({
    id: '/$journalId/bookmarked',
    path: '/$journalId/bookmarked',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutJournalIdTagsTagIdRoute =
  LayoutJournalIdTagsTagIdRouteImport.update({
    id: '/$journalId/tags/$tagId',
    path: '/$journalId/tags/$tagId',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutRouteWithChildren
  '/create-journal': typeof CreateJournalRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/$journalId/bookmarked': typeof LayoutJournalIdBookmarkedRoute
  '/$journalId/notes': typeof LayoutJournalIdNotesRoute
  '/$journalId/tasks': typeof LayoutJournalIdTasksRoute
  '/$journalId/updates': typeof LayoutJournalIdUpdatesRoute
  '/$journalId/tags/$tagId': typeof LayoutJournalIdTagsTagIdRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutRouteWithChildren
  '/create-journal': typeof CreateJournalRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/$journalId/bookmarked': typeof LayoutJournalIdBookmarkedRoute
  '/$journalId/notes': typeof LayoutJournalIdNotesRoute
  '/$journalId/tasks': typeof LayoutJournalIdTasksRoute
  '/$journalId/updates': typeof LayoutJournalIdUpdatesRoute
  '/$journalId/tags/$tagId': typeof LayoutJournalIdTagsTagIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/create-journal': typeof CreateJournalRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_layout/$journalId/bookmarked': typeof LayoutJournalIdBookmarkedRoute
  '/_layout/$journalId/notes': typeof LayoutJournalIdNotesRoute
  '/_layout/$journalId/tasks': typeof LayoutJournalIdTasksRoute
  '/_layout/$journalId/updates': typeof LayoutJournalIdUpdatesRoute
  '/_layout/$journalId/tags/$tagId': typeof LayoutJournalIdTagsTagIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-journal'
    | '/login'
    | '/signup'
    | '/$journalId/bookmarked'
    | '/$journalId/notes'
    | '/$journalId/tasks'
    | '/$journalId/updates'
    | '/$journalId/tags/$tagId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-journal'
    | '/login'
    | '/signup'
    | '/$journalId/bookmarked'
    | '/$journalId/notes'
    | '/$journalId/tasks'
    | '/$journalId/updates'
    | '/$journalId/tags/$tagId'
  id:
    | '__root__'
    | '/_layout'
    | '/create-journal'
    | '/login'
    | '/signup'
    | '/_layout/$journalId/bookmarked'
    | '/_layout/$journalId/notes'
    | '/_layout/$journalId/tasks'
    | '/_layout/$journalId/updates'
    | '/_layout/$journalId/tags/$tagId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  CreateJournalRoute: typeof CreateJournalRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-journal': {
      id: '/create-journal'
      path: '/create-journal'
      fullPath: '/create-journal'
      preLoaderRoute: typeof CreateJournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/$journalId/updates': {
      id: '/_layout/$journalId/updates'
      path: '/$journalId/updates'
      fullPath: '/$journalId/updates'
      preLoaderRoute: typeof LayoutJournalIdUpdatesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$journalId/tasks': {
      id: '/_layout/$journalId/tasks'
      path: '/$journalId/tasks'
      fullPath: '/$journalId/tasks'
      preLoaderRoute: typeof LayoutJournalIdTasksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$journalId/notes': {
      id: '/_layout/$journalId/notes'
      path: '/$journalId/notes'
      fullPath: '/$journalId/notes'
      preLoaderRoute: typeof LayoutJournalIdNotesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$journalId/bookmarked': {
      id: '/_layout/$journalId/bookmarked'
      path: '/$journalId/bookmarked'
      fullPath: '/$journalId/bookmarked'
      preLoaderRoute: typeof LayoutJournalIdBookmarkedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$journalId/tags/$tagId': {
      id: '/_layout/$journalId/tags/$tagId'
      path: '/$journalId/tags/$tagId'
      fullPath: '/$journalId/tags/$tagId'
      preLoaderRoute: typeof LayoutJournalIdTagsTagIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutJournalIdBookmarkedRoute: typeof LayoutJournalIdBookmarkedRoute
  LayoutJournalIdNotesRoute: typeof LayoutJournalIdNotesRoute
  LayoutJournalIdTasksRoute: typeof LayoutJournalIdTasksRoute
  LayoutJournalIdUpdatesRoute: typeof LayoutJournalIdUpdatesRoute
  LayoutJournalIdTagsTagIdRoute: typeof LayoutJournalIdTagsTagIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutJournalIdBookmarkedRoute: LayoutJournalIdBookmarkedRoute,
  LayoutJournalIdNotesRoute: LayoutJournalIdNotesRoute,
  LayoutJournalIdTasksRoute: LayoutJournalIdTasksRoute,
  LayoutJournalIdUpdatesRoute: LayoutJournalIdUpdatesRoute,
  LayoutJournalIdTagsTagIdRoute: LayoutJournalIdTagsTagIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  CreateJournalRoute: CreateJournalRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
